
/* imported from extra_tokens.inc */
#define TK_CUSTOM 250 /*TODO: get the last number automatically */
#define TK_FUNCTION (TK_CUSTOM + 1)
#define TK_UMINUS   (TK_CUSTOM + 2)
#define TK_UPLUS    (TK_CUSTOM + 3)
#define TK_ISNOT    (TK_CUSTOM + 4)

#define TK_PROPERTY (TK_CUSTOM + 8)
#define TK_PROPERTY_START (TK_CUSTOM + 9)
#define TK_PROPERTY_END (TK_CUSTOM + 10)
#define TK_MYSQL_HINT (TK_CUSTOM + 11)
#define TK_NOT_HANDLED (TK_CUSTOM + 12)